name: transformer_page_view_new
description: PageTransformer for flutter
version: 0.1.0
homepage:  https://github.com/qssq/transformer_page_view_new

environment:
  sdk: ">=2.15.0 <3.0.0"
  # sdk: ">=2.0.0-dev.50.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
